### ISSUE TITLE
Support italian language

### ISSUE THREAD

**Issue by pharaone** [bhdouglass/finger-painting#1]
Please support italian language

**Comment by bhdouglass** [comment]
I'm trying to figure out why the translation files are not being generated properly. But once they are then I'll be open for translations.

**Comment by pharaone** [comment]
Thanks

**Comment by bhdouglass** [comment]
I've just uploaded version 2.0, which is now translatable, check out the project on launchpad if you want to translate it: https://translations.launchpad.net/finger-painting
