### ISSUE TITLE
Changing colour manually

### ISSUE THREAD

**Issue by Jon-of-Kent** [bhdouglass/finger-painting#2]
Hello,

This is a brilliant little app - thank you.  I am stuck with something though, which is how to change colour using the presets it gives you.  I expected it to select the colour when I press one, but it takes you straight to the palette.  Am I missing something?  Or is the idea that you use colour no. 1 all the time and keep changing it as you go?

I realise you've written this for children, so my apologies for what must be a very dim-witted question..!

**Comment by bhdouglass** [comment]
No worries! I realize now that the labels aren't very clear. The colors 1-10 are different colors per finger (since its multi-touch enabled). So to change the primary color (color 1) tap color 1 then choose a color from the palette.
